[package]
name        = "flix-specialization-names-lab"
description = "Flix stable specialization names lab"
version     = "0.1.0"
flix        = "0.75.2"
license     = "Apache-2.0"
authors     = ["Werner Stein <werner.stein@gmail.com>"]
